apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-sa
  namespace: stonksco
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: stonksco
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: stonksco
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adminer-sa
  namespace: stonksco
automountServiceAccountToken: false
